# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: crypto
---
# Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crypto-storage
  namespace: crypto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Producer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: crypto
  labels:
    app: producer
    tier: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
        tier: data-ingestion
    spec:
      containers:
      - name: producer
        image: europe-west2-docker.pkg.dev/crypto-anomaly-detection/crypto/crypto-producer:v8
        command: ["python", "kafka_producer.py"]
        envFrom:
        - secretRef:
            name: kafka-credentials
        env:
        - name: ENV_MODE
          value: "GKE"
        - name: REGION
          value: "europe-west2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          exec:
            command:
            - pgrep
            - python
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - pgrep
            - python
          initialDelaySeconds: 10
          periodSeconds: 10
---
# Detector Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
  namespace: crypto
  labels:
    app: detector
    tier: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
        tier: processing
    spec:
      initContainers:
      - name: init-data-dir
        image: busybox:1.36
        command: ["sh", "-c", "mkdir -p /data/output && chmod -R 777 /data"]
        volumeMounts:
        - name: storage
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      containers:
      - name: detector
        image: europe-west2-docker.pkg.dev/crypto-anomaly-detection/crypto/crypto-detector:v8
        command: ["python", "detect.py"]
        envFrom:
        - secretRef:
            name: kafka-credentials
        env:
        - name: DATABASE_PATH
          value: "/data/output/trading_anomalies.db"
        - name: TRADES_CSV
          value: "/data/output/trades.csv"
        - name: ANOMALIES_CSV
          value: "/data/output/anomalies.csv"
        - name: ENV_MODE
          value: "GKE"
        - name: REGION
          value: "europe-west2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: storage
          mountPath: /data
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          exec:
            command:
            - pgrep
            - python
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - pgrep
            - python
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: crypto-storage
---
# Dashboard Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: crypto
  labels:
    app: dashboard
    tier: visualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
        tier: visualization
    spec:
      containers:
      - name: dashboard
        image: europe-west2-docker.pkg.dev/crypto-anomaly-detection/crypto/crypto-dashboard:v6
        command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
        ports:
        - containerPort: 8501
          name: http
        volumeMounts:
        - name: storage
          mountPath: /data
        env:
        - name: ENV_MODE
          value: "GKE"
        - name: REGION
          value: "europe-west2"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: crypto-storage
---
# Dashboard Service
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: crypto
  labels:
    app: dashboard
spec:
  selector:
    app: dashboard
  ports:
  - port: 8501
    targetPort: 8501
    name: http
  type: ClusterIP
